trigger:
- main  # Trigger the pipeline on changes to the 'main' branch

pool:
  name: 'windows'  # Use the name of your self-hosted agent pool
  demands:
    - agent.os -equals Windows_NT  # Ensure the build runs on a Windows-based machine

jobs:
- job: Build_and_Deploy
  steps:

    # Step 1: Install Java 8 if it's not installed
    - task: PowerShell@2
     
    # Step 3: Verify Java installation
    - task: PowerShell@2
      displayName: 'Check Java Installation'
      inputs:
        targetType: 'inline'
        script: |
          java -version  # Verify Java version
          javac -version  # Verify javac version

    # Step 4: Compile Java code
    - script: |
        echo "Compiling Java code..."
        # Compile Java source code located in 'src' folder
        javac -d $(Build.SourcesDirectory)/bin src/**/*.java
      displayName: 'Compile Java Code'

    # Step 5: Run the Java application (assuming 'Calculator' is the main class)
    - script: |
        echo "Running the Java application..."
        # Run Java application (replace 'Calculator' with your main class)
        java -cp $(Build.SourcesDirectory)/bin Calculator
      displayName: 'Run Java Application'

    # Optional Step 6: Copy compiled files to staging directory
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/bin'  # Path to compiled files
        Contents: '**/*.class'  # Include all .class files
        TargetFolder: '$(Build.ArtifactStagingDirectory)'  # Staging directory for artifacts

    # Optional Step 7: Publish build artifacts (if needed)
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'drop'  # Name of the artifact
        targetPath: '$(Build.ArtifactStagingDirectory)'  # Path to the compiled .class files
